  server:
  port: 8006
spring:
  application:
    name: sim-cache-server
  datasource:
    url: jdbc:h2:file:~/database/sim-db-query;AUTO_SERVER=true;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema:
      - classpath:db/init.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+16
mybatis:
  mapperLocations: classpath*:com/yao2san/**/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
