server:
  port: 8011
spring:
  datasource:
    url: jdbc:h2:file:~/database/sim;AUTO_SERVER=true;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema:
      - classpath:db/init.sql
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2
app:
  config:
    login-url: http://127.0.0.1:9527/#/login
    not-found-url: http://127.0.0.1:9528/#/404
    local-temp-file-dir: D:/tmp/